version: '3.7'
networks:
  app-tier:
    driver: bridge
services:
  mytul-db:
    image: postgres:12
    restart: unless-stopped
    container_name: mytul-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mytul-db
    ports:
      - 5433:5432
    volumes:
      - mytul-db:/var/lib/postgresql/data:rw
  mytul-mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mytul-db: {}
